name: Build template

trigger:
  - master
pr:
  branches:
    include:
    - '*'

stages:
- stage: Build
  jobs:
  - job: Linux
    pool:
      vmImage: ubuntu-latest
    steps:
      - template: .ci/utils/use-node.yml
      - template: .ci/utils/use-esy.yml
      - script: mkdir $(Pipeline.Workspace)/morph-hello-world
        displayName: "Create project folder"
      - script: "pesy --template=reason-native-web/morph-hello-world-pesy-template"
        displayName: "Initialize pesy template"
        workingDirectory: $(Pipeline.Workspace)/morph-hello-world
      - script: "esy test"
        displayName: "Run tests"
        workingDirectory: $(Pipeline.Workspace)/morph-hello-world

  - job: macOS
    pool:
      vmImage: macOS-latest
    steps:
      - template: .ci/utils/use-node.yml
      - template: .ci/utils/use-esy.yml
      - script: mkdir $(Pipeline.Workspace)/morph-hello-world
        displayName: "Create project folder"
      - script: "pesy --template=reason-native-web/morph-hello-world-pesy-template"
        displayName: "Initialize pesy template"
        workingDirectory: $(Pipeline.Workspace)/morph-hello-world
      - script: "esy test"
        displayName: "Run tests"
        workingDirectory: $(Pipeline.Workspace)/morph-hello-world
  
  # - job: Windows
  #   pool:
  #     vmImage: windows-latest
  #   steps:
  #     - template: .ci/utils/use-node.yml
  #     - template: .ci/utils/use-esy.yml
  #     - script: mkdir $(Pipeline.Workspace)/morph-hello-world
  #       displayName: "Create project folder"
  #     - script: "pesy --template=reason-native-web/morph-hello-world-pesy-template"
  #       displayName: "Initialize pesy template"
  #       workingDirectory: $(Pipeline.Workspace)/morph-hello-world
  #     - script: "esy test"
  #       displayName: "Run tests"
  #       workingDirectory: $(Pipeline.Workspace)/morph-hello-world
